name: CI/CD Workflow

on:
  push:
    # branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
    # paths:
    #   - 'ecommerce_customer_churn_dataset_raw.csv' 

# Set variable global agar konsisten
env:
  # Menggunakan path absolut untuk tracking URI
  MLFLOW_TRACKING_URI: "sqlite:///${{ github.workspace }}/mlruns.db"
  EXPERIMENT_NAME: "ci_retrain_model"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Kita butuh library ini di environment runner agar bisa setup experiment
          pip install mlflow pandas scikit-learn numpy

      - name: Setup MLflow Experiment
        run: |
          # Step ini khusus untuk membuat struktur folder mlruns dan mendaftarkan experiment
          python -c "
          import mlflow
          mlflow.set_tracking_uri('${{ env.MLFLOW_TRACKING_URI }}')
          mlflow.set_experiment('${{ env.EXPERIMENT_NAME }}')
          print(f'Experiment {{ env.EXPERIMENT_NAME }} created successfully at {{ env.MLFLOW_TRACKING_URI }}')
          "

      - name: Run mlflow project
        run: |
          # Kita pass nama experiment ke dalam mlflow run
          mlflow run MLProject/ --env-manager=local --experiment-name ${{ env.EXPERIMENT_NAME }}

      - name: Get latest MLflow run_id
        run: |
          # Mengambil Run ID terakhir dari experiment yang spesifik
          RUN_ID=$(python -c "
          import mlflow
          mlflow.set_tracking_uri('${{ env.MLFLOW_TRACKING_URI }}')
          experiment = mlflow.get_experiment_by_name('${{ env.EXPERIMENT_NAME }}')
          runs = mlflow.search_runs(experiment_ids=[experiment.experiment_id])
          print(runs.iloc[0].run_id)
          ")
          
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      - name: Upload MLflow results to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-experiment-results
          path: |
            mlruns.db
            mlartifacts/
            mlruns/
          if-no-files-found: warn

      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "submission-msml" 

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Tag the Docker image
      - name: Tag Docker Image
        run: |
          docker tag submission-msml ${{ secrets.DOCKER_HUB_USERNAME }}/submission-msml:latest

      # Push Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/submission-msml:latest

